spring:
  profiles:
    active: '@env@'

  jackson:
    date-format: YYYY-MM-dd
    time-zone: GMT+8

logging:
  config: classpath:logback-spring.xml

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.demo.entity

